apiVersion: v2
name: presto
description: The official Helm chart for Presto
type: application
version: 0.4.0
appVersion: "0.292"
home: https://prestodb.io
icon: https://prestodb.io/docs/current/_static/logo.png
keywords:
  - presto
  - prestodb
sources:
  - https://github.com/prestodb/presto
  - https://github.com/prestodb/presto-helm-charts
